### ISSUE TITLE
今日はプロ

### ISSUE THREAD

**Issue by yuha-yuha** [yuha-yuha/2023KosenFes_KosenGo#26]
ここで会話

**Comment by Meri11Ra1** [comment]
# プロ怖いな
---
イシュー番号無駄なやつが増えるし、クローズしても履歴が残る最高の会話場所

**Comment by yuha-yuha** [comment]
**PUROPURO!!!ぎゃーーーー！！！**

**Comment by Meri11Ra1** [comment]
きもちーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーー

**Comment by Meri11Ra1** [comment]
# いしずー
人間すごいな、こんなにまずいのど飴でも適応できてきた

**Comment by Chuseshi-rookie** [comment]
おまえらやばい

**Comment by yuha-yuha** [comment]
プロ終わり

**Comment by Chuseshi-rookie** [comment]
puroowatta
